module.exports.authService = require('./auth.service')
module.exports.taskService = require('./task.service')
module.exports.tokenService = require('./token.service')
module.exports.userService = require('./user.service')
module.exports.accountService = require('./account.service')
module.exports.campaignService = require('./campaign.service')
module.exports.profileService = require('./profile.service')
module.exports.uploadService = require('./upload.service')
module.exports.mailService = require('./mail.service')

